export const Patrimonio = [
    {
      name: 'Casabe de Yuca',
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      description: 'Si buscas un postre que tenga ingredientes autóctonos del territorio, el casabe de yuca te dejará sorprendido. Diferentes investigaciones han determinado que la yuca tiene más de cinco mil años incluso, más antiguo que el maíz y que cuando los colonizadores llegaron al territorio, este alimento ya se encontraba en la zona, es decir, no fue un producto de la colonización.\nLa historia detrás del casabe es única y es que sus preparaciones son antiquísimas. El cazabe nace como una necesidad porque existían dos tipos de yuca: la yuca brava que era venenosa y la yuca dulce, que se podía consumir. En la mayoría del territorio se encontraba la yuca brava y por esa razón, para consumir el casabe existe toda una preparación detrás para poder consumirla.\nY como dato curioso, en tiempos coloniales, el casabe se convirtió en una preparación muy importante para la dieta española debido a que es un alimento que se conserva mucho y era muy útil para los navegantes de los viajes transatlánticos, y que además, se le daba mucho a la población esclavizada.',
      line: 'Autóctono',
      latitude: 10.423116100488615,
      longitude: -75.54901353395378,
      images: ['/assets/casabe (1).jpg', '/assets/casabe (1).png', '/assets/casabe (2).jpg'],
      ref : 'Tomada de Soy Pacha Mama. https://soypachamama.co/producto/tortillas-crujientes-de-yuca-casabe/'
    },
    {
      name: 'Posta Cartagenera',
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      description: 'La cocina es un arte, obra de la creatividad de cocineras del pueblo que transmiten sus conocimientos, crean y perfeccionan los platillos de generación en generación. Es así como nace la reconocida posta cartagenera, un platillo con raíces coloniales. Según cuenta la leyenda, su origen se remonta a la equivocación de una cocinera al dejar quemar la carne. Quien, para remediarlo, decidió añadir salsas y condimentos que disiparon el sabor. Desde ahí, el famoso plato cartagenero ha tomado fama, siendo preparado, generalmente, con punta de anca. Este corte se deja cocinar lentamente con clavos de olor, cebolla cabezona, cebolla puerro, cebolla larga, zanahoria, pimienta, sal y ajo. Además, se agrega panela, vino tinto y, en algunos casos, pony malta para otorgar un sabor dulzón. La posta cartagenera es reconocida por su color negro y su capa dura. Finalmente, para darle un toque caribeño tradicional, viene acompañada por yuca o patacones y arroz de coco.',
      line: 'Autóctono',
      latitude: 10.436263272967182,
      longitude: -75.52730375496118,
      images: ['/assets/Posta cartagenera.jpeg'], 
      ref : ''
    },
    {
      name: 'Arepa de huevo',
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      description: 'Producto de una herencia culinaria bañada por la tradición del maíz indígena, las tortillas de huevos españolas y la sazón africana en frituras (Cabrera, 2024). Cada bocado de la arepa de huevo es el símbolo de una historia de diversidad cultural y gastronómica de la región caribe. Pasado de generación en generación la arepa de huevo se ha vuelto el medio de emprendimiento de muchas mujeres costeñas de economías populares: a través de pilar el maíz, cocinarlo, amasarlo “bien amasaito”, fritarlo y agregarle un huevo hasta que la arepa este doradita sacan el sustento para sus familias (Una historia con sabor arepa de huevo, s/f). ',
      line: 'Tradicional',
      latitude: 10.420796542694731,
      longitude: -75.54698896497104,
      images: ['/assets/arepa-h1.jpeg','/assets/arepa-h2.jpeg'],
      ref : ''
    },
    {
      name: 'Buñuelo de frijolito',
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      description: 'Hace aproximadamente ocho mil años en América Latina se dió el origen de uno de los alimentos más básicos de la cultura indígena, los frijoles (Hernández-López et al., 2013). En la actualidad existen diferentes tipos de frijol; no obstante, en la región caribe y específicamente en Cartagena, el frijolito blanco cabecita negra es muy importante para la identidad de los cartageneros. Cuentan que existe un plato muy importante que se realiza con esta legumbre: el buñuelo de frijolito blanco cabecita negra. Este buñuelo no se consigue fácilmente y muchos de los cartageneros esperan hasta el festival del frito para degustar uno de sus platos favoritos. Diana Jimenez, egresada del programa de cocina de la Escuela Taller de Cartagena nos contó la importancia de este buñuelo. Principalmente es un frito que no se ve en el interior del país, por lo que es bastante importante en Cartagena y como se mencionó antes, no se consigue fácilmente. Su preparación es bastante compleja: el frijolito primero se limpia y se friega durante tres días, cambiando el agua cada día ya que durante este proceso, el agua se va evaporando. Después, se quita la piel al frijol fregado y se muele. Una vez molido, se agrega sal y se mezcla bien. Por último, se cocina la masa resultante. Por esa extensa preparación no todas las personas lo hacen; ya que, las que lo hacen suelen tener una larga tradición en la preparación de este plato.',
      line: 'Tradicional',
      latitude: 10.426282133897164,
      longitude: -75.54836615577806,
      images: ['/assets/Buñuelo de frijolito.png'],
      ref : ''
    },
    {
      name: 'Buñuelo de maíz',
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      description: 'El buñuelo de maíz, es una delicia gastronómica que ha cautivado el paladar de los cartageneros por generaciones. Doña Piedad, vendedora de buñuelos con 40 años de experiencia, lo describe como un legado familiar que ha pasado de madres a hijas, conservando su receta y sabor auténtico. Este manjar se elabora principalmente con masa de maíz, cuidadosamente mezclada con otros ingredientes como queso y huevos, dando como resultado una textura crujiente por fuera y suave por dentro. La técnica culinaria transmitida de generación en generación, lo convierte en una comida única. El buñuelo de maíz es una manifestación de la diversidad culinaria de la región Caribe. Su presencia en festividades y celebraciones, como Navidad o Semana Santa. Doña Piedad, asegura que el buñuelo de maíz seguirá siendo parte de la identidad cartagenera, que se transmite de generación en generación.',
      line: 'Tradicional',
      latitude: 10.423675759693122,
      longitude: -75.5503285423284,
      images: ['/assets/buñuelo-maiz.jpeg'],
      ref : ''
    },
    {
      category: "Patrimonio Inmaterial",
      subcategory: "Fogón Cartagenero",
      line: "Tradicional",
      name: " Pastel Cartagenero",
      description: "El pastel cartagenero es una combinación de diferentes alimentos entre los que se resalta el arroz, la berenjena, la aceituna, zanahoria, papa, entre otros. Esta delicia también viene acompañado de una o varias proteínas a base de pollo, carne, cerdo o gallina.\nEste pastel tiene gran importancia para la ciudad debido a que su origen que se remonta a la época de la colonia y nace en las festividades de la navidad. Los amos de aquella época organizaban las comidas y traían gallina, cerdo y todo lo necesario para la celebración. Pero siempre sobraba comida y estas sobras se las daban a los esclavos. Los esclavos la guardaban en hojas de plátano o de bijao con el fin de conservar la comida por varios días (Radio Nacional de Colombia, 2021).\nEl pastel cartagenero no solo es un plato exquisito, sino que es una expresión cultural que se ha arraigado en las tradiciones de la ciudad y es tan su relevancia cultural que cuenta con su propio Festival.De hecho, el pastel cartagenero ha sido reconocido como parte del programa “Patrimonio Inmaterial de Cartagena” lo que avala su importancia como legado de la ciudad.",
      images: ['/assets/Posta cartagenera.jpeg'],
      latitude: 10.393350945844881, 
      longitude: -75.48272574691944,
      ref: "Foto tomada de: Radio Nacional de Colombia. https:\/\/www.radionacional.co\/cultura\/gastronomia\/festival-del-pastel-en-cartagena-tradicion-desde-1987     2. Foto tomada de: Caracol Radio. https:\/\/caracol.com.co\/emisora\/2016\/12\/24\/cartagena\/1482598810_689843.html"
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Tradicional',
      name: 'Plátano en tentación',
      description: 'En las costas colombianas, donde el sol se encuentra con el mar , nace una historia culinaria protagonizada por el plátano macho. Lejos de ser un simple banano, el plátano macho, con su piel verde intenso y corazón blanco, encierra un universo de sabor y tradición. Su origen se remonta a las lejanas tierras asiáticas, desde donde emprendió un viaje a través de continentes, adaptándose a los climas tropicales y subtropicales de América Latina (El País, 2020). En Colombia, encontró un hogar en las mesas costeras, donde su versatilidad lo convirtió en un ingrediente esencial. Creando manjares como el patacón y las moneditas. \n\nPero el verdadero despertar del sabor del plátano macho llega con el \'plátano en tentación\', también conocido como \'plátano maduro\' o \'plátano pícaro\'. para el cual se debe dejar madurar el plátano hasta que se vea amarillento por fuera. Este postre o acompañamiento cartagenero por excelencia, fusiona la dulzura madura del plátano con el toque y tono chispeante de la Kola Román, una bebida nacida del ingenio local.\n\nLa historia cuenta que la Kola Román, la original, surgió del laboratorio de los Román en Cartagena, y que fue usada para impregnar al plátano de una magia especial. Un viaje al pasado, a la esencia de Cartagena, donde la tradición se fusiona con el sabor. Ya que, para su preparación se caracteriza por contener este peculiar ingrediente, más otros como azúcar, canela o vino. Este postre no solo deleita el gusto, sino que también evoca la cultura champetua, con sus pasos contagiosos y su alegría contagiosa.Es un poema culinario que narra la historia de un pueblo, de sus calles y su gente. Un homenaje a la creatividad cartagenera, donde la simpleza se transforma en una obra maestra del sabor. El plátano en tentación con Kola Román, más que un postre, es una experiencia sensorial que te atrapa y te transporta al corazón de Cartagena.\n',
      images: ['/assets/Plátano en tentación.jpg'],
      latitude: 10.436263272967182, 
      longitude: -75.52730375496118,
      ref: ''
     },
  

     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Tradicional',
      name: 'Dulces Tradicionales',
      description: "“Alegría con coco y aní\nCasera cómpreme a mí,\nque vengo del barrio de Getsemaní.”\n\nEsos son los versos que canta Damaris y que cantó su mamá Dionisia por mucho tiempo cuando vendía alegrías. Ahora Damaris los comparte con los niños de La Puntilla (su barrio), porque los escuchan cada vez que una palenquera pasa vendiendo. Transmitiendo historias que esos versos guardan de generación en generación (Mujeres, tradición y sazón, 2018). Los dulces tradicionales de la costa son el resultado de una mezcla cultural, compuesta por la fuente culinaria africana, indígena y española. Por un lado los indígenas usaban el dulce natural de las frutas más la miel, sin embargo también se usaron derivados de la caña de azúcar (planta traída por los españoles) como el azúcar y la panela (El Heraldo, 2016). Históricamente, estos dulces han sido vendidos por palenqueras en grandes poncheras que llevan en su cabeza, recitando versos como el mencionado al principio.\nActualmente, existen una gran variedad de dulces, recetas que se han ido perfeccionando de generación en generación como lo demuestra Neila Pérez, una cocinera palenquera que, haciendo dulces, menciona que los vende hace más de 20 años (El Heraldo 2016) asimismo comenta: “Yo aprendí a hacer los dulces viendo a mi mamá, que trabajaba en esto también. El toquecito final pa’ los dulces se los pone uno, eso es un secreto que si tú lo das, pierdes el año” (El Heraldo, parr. 3, 2016). Estos famosos dulces tradicionales se pueden conseguir principalmente en épocas de Semana Santa en toda la ciudad. Sin embargo, en el portal de los dulces, ubicado en el centro histórico de Cartagena, se pueden encontrar todos los días.\n\nDulce de ñame\nEsta exquisita combinación de ñame cocido en leche, con azúcar y especias, es un dulce tradicional de la costa colombiana. Es preparado específicamente en épocas de Semana Santa y, entre todos las variedades, es uno de los más reconocidos. Se recomienda buscar este famoso dulce en las fechas en las que se celebre el festival del dulce cartagenero en la ciudad. Este puede ser encontrado en el Biblioparque San Francisco y el portal de los dulces.\n\nDulce de papa\nEn la actualidad la papa es muy importante en la alimentación de los colombianos. Tuvo su origen en la región Andina y fue descubierto por los conquistadores en el año 1537 en la provincia de Vélez. Su preparación es sencilla: se debe quitar la cáscara a las papas y cocerlas hasta que estén completamente blandas. Luego, se mezcla en la licuadora con leche y se añade panela, azúcar, canela y clavos. Por último, todo se cocina a fuego medio hasta que la mezcla espese (Carvajal, A., 2023).\n\nDulce de guayaba\nLa guayaba es una fruta originaria de centro y sur américa. Con ella se realiza un dulce muy apreciado en Cartagena y la costa caribe. Para hacer este dulce de guayaba, se lavan y cortan las guayabas, se hierven hasta que estén blandas, se cuelan y se dejan enfriar. Luego se trituran en la licuadora sin agua y se pasa la mezcla por un colador para quitar las pepas. Se debe añadir panela y dejar hervir nuevamente hasta que se derrita. Por último, se deja enfriar y se sirve con galletas saladas o pan.\n\nDulce de yuca\nEl dulce de yuca, un postre tradicional de la región Caribe colombiana, es fruto de la paciente elaboración artesanal a partir de la yuca, una raíz tuberosa propia de estas tierras. Este dulce, que se presenta en diversas variedades de sabores frutales, aportando un toque caribeño irresistible, se ha convertido en un ícono gastronómico de Cartagena y la región. Su origen se remonta a la sabiduría culinaria de las matronas costeñas, quienes generación tras generación han transmitido la receta, preservando así un legado de sabor y tradición. \n\nDulce de papaya\nEl dulce de papaya, un postre tradicional de la cultura caribeña. Elaborado a partir de papaya verde o madura, este dulce se cocina utilizando azúcar y, en ocasiones, especias como canela o clavo de olor, para exaltar su sabor y aroma. Si bien el dulce de papaya ostenta el título de patrimonio inmaterial de Venezuela, su encanto ha traspasado fronteras, convirtiéndose en un postre tradicional en la región hermana del Caribe colombiano. Su presencia en las mesas caribeñas es un símbolo de la conexión cultural que existe entre estos dos países, un puente dulce que une tradiciones y sabores. \n\nDulce de corozo\nCuando llega la Semana Santa, el dulce de corozo es uno de los más apetecidos. Y es que su delicioso sabor agridulce cautiva el paladar de todos los turistas que tienen la oportunidad de probarlo y que con buena razón, se convierte en uno de los favoritos. Pero lo que hace que el dulce de corozo sea aún más especial es su exclusividad y es que pocos países del mundo cuentan con la fortuna de que este fruto crezca en su territorio, y para suerte de nosotros, Colombia tiene la dicha de ser uno de ellos, pero crece específicamente en la Costa Caribe. \n\nMongo mongo\nEs un postre hecho a base de plátano, maduro, pera, mamey, tamarindo, corozo, grosella, ciruela, jengibre y panela (El Pillón, 2022). Se cree que se originó por la necesidad de conservar las frutas con las cuales se elabora. A pesar de que tradicionalmente se prepara y consume en Semana Santa(Adiela Beatriz Cordero Rivero, 2016), ya se pueden encontrar en lugares como en el Portal de Dulce, aunque su oferta está limitada debido a su compleja preparación. \n\n",
      
      images: ['/assets/corozo.png','/assets/Dulce de ñame.jpg','/assets/Dulce de papa.png','/assets/Dulce de papaya.jpeg','/assets/Dulce de Yuca.jpeg'],
      latitude: 10.423080893755614, 
      longitude: -75.54958150640972,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Tradicional',
      name: 'Arroz de titote',
      description: 'El arroz de titote, un plato emblemático de Cartagena, es un ejemplo de la rica mezcla cultural que caracteriza a la cocina afrocolombiana y el caribe colombiano. Sus orígenes se remontan a la llegada de los españoles a América, quienes trajeron consigo el arroz desde Asia. El coco, por otro lado, se presume que llegó desde las islas del Pacífico Sur, específicamente de India y Tailandia. Sin embargo, es importante reconocer el papel fundamental que jugaron los africanos en la creación de este plato. Según el libro \'Fogón Caribe. La Historia de la Cocina del Caribe Colombiano\' (ARROZ CON COCO TITOTÉ [CARIBE DE COLOMBIA, 2023) fueron ellos quienes enseñaron a los nativos el uso del aceite de coco para freír y guisar, de la leche para dar sabor a platos salados y dulces, y de la pulpa para elaborar deliciosos postres. El arroz de titote se prepara con arroz cocido, coco rallado y agua de coco. El titote, que le da nombre al plato, es la caramelización de la leche de coco, lo que le confiere un sabor dulce y un aroma característico. Más allá de su sabor delicioso, el arroz de titote es un símbolo de la herencia afrocolombiana y su contribución a la cultura culinaria de Colombia.',
      images: ['/assets/Arroz de titote.png'],
      latitude: 10.436444465279221, 
      longitude: -75.52764290248962,
      ref: 'Foto tomada de : By otoya https:\/\/byotoya.com\/arroz-con-coco\/'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Tradicional',
      name: 'Arroz de cangrejo',
      description: 'El mar es una parte fundamental de la identidad cartagenera y se ve reflejado ampliamente en sus platos característicos. Uno de ellos es el arroz de cangrejo: es importante que este plato se realice con cangrejos azules que se consiguen con facilidad en época de lluvias en La Boquilla, Tierrabomba y Barú. El arroz de cangrejo es muy apetecido en Cartagena y los mejores se encuentran en el mercado de Bazurto y Getsemaní. \n\nPara preparar este plato, primero se limpia minuciosamente el cangrejo, quitándole el pechito, las patitas y las huevitas (que dan el sabor). Se lava bien con un cepillo para eliminar la arena hasta que el agua salga limpia. Luego, se hierve el cangrejo con un toque secreto: el zumo de coco. Una vez que los cangrejos están cocidos, se sacan de la olla y se agregan al arroz preparado aparte. Es importante escoger más hembras que machos, ya que estas aportan las \'huevitas\' que dan sabor y color al arroz. La limpieza es fundamental para evitar que el arroz quede amargo, por lo que se recomienda lavarlos bien para sacar las huevas sin cortar mal el cuerpo y derramar la hiel. Este plato es típico de la Calle Lomba en Getsemaní (El Getsemanicense, 2018).\n',
      images: ['/assets/Arroz de cangrejo.png'],
      latitude: 10.412195167654444, //10.419286690732788,
      longitude: -75.52495504180679, //-75.5446459841237,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Tradicional',
      name: 'Arroz de cangrejo',
      description: 'El mar es una parte fundamental de la identidad cartagenera y se ve reflejado ampliamente en sus platos característicos. Uno de ellos es el arroz de cangrejo: es importante que este plato se realice con cangrejos azules que se consiguen con facilidad en época de lluvias en La Boquilla, Tierrabomba y Barú. El arroz de cangrejo es muy apetecido en Cartagena y los mejores se encuentran en el mercado de Bazurto y Getsemaní. \n\nPara preparar este plato, primero se limpia minuciosamente el cangrejo, quitándole el pechito, las patitas y las huevitas (que dan el sabor). Se lava bien con un cepillo para eliminar la arena hasta que el agua salga limpia. Luego, se hierve el cangrejo con un toque secreto: el zumo de coco. Una vez que los cangrejos están cocidos, se sacan de la olla y se agregan al arroz preparado aparte. Es importante escoger más hembras que machos, ya que estas aportan las \'huevitas\' que dan sabor y color al arroz. La limpieza es fundamental para evitar que el arroz quede amargo, por lo que se recomienda lavarlos bien para sacar las huevas sin cortar mal el cuerpo y derramar la hiel. Este plato es típico de la Calle Lomba en Getsemaní (El Getsemanicense, 2018).\n',
      images: ['/assets/Arroz de cangrejo.png'],
      latitude: 10.419286690732788,
      longitude: -75.5446459841237,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Mote de queso',
      description: 'El plato encuentra su predecesor en el denominado mote candela, compuesto por ingredientes como el ñame, cebolla, ajo y sal (Flórez, 2023). Este plato tiene sus raíces en los días de guerra de la nación colombiana en el siglo XX con la denominada \'Guerra de los mil días\'. En medio de la lucha, el ejército del general Rafael Uribe Uribe, vencido, sufriendo de hambre y en penurias, encontró en el departamento de Sucre una forma de mitigar el hambre a través del ñame (ingrediente principal) (Flórez, 2023). Con el paso del tiempo, debido a la falta de proteínas de calidad, se introdujo el queso (Bonilla, 2024). Así, con el queso, el ñame, la cebolla, el ajo, la sal y, finalmente, el suero costeño, se gestó el mote de queso, convirtiéndose en la identidad gastronómica de una región fuerte y agrícola.',
      images: ['/assets/mote.jpeg'],
      latitude: 10.436455016624596, 
      longitude: -75.52765363256728,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Arroz de coco',
      description: 'Este acompañamiento es una de las insignias de la interculturalidad entre africanos, árabes e indígenas. El arroz proviene de los árabes y lo introdujeron en España en el siglo VIII, que a su vez, lo introdujeron en América pero su cultivo estuvo a manos de africanos. Mientras que el coco tiene sus orígenes en el Sureste Asiatico y que posteriormente se diversifica por todo el Pacifico para después llegar al continente africano y de allí, llegar al continente americano entre los siglos XVI-XVII (Regmurcia Integra Digital, s.f.). \nCon la llegada de estos dos alimentos, se presentó una fusión entre el arroz y el coco en la costa de Colombia, donde había presencia de población afro . \nHoy en día, se vuelve un acompañamiento imprescindible en los platos típicos de la ciudad.',
      images: ['/assets/arroz de coco.png'],
      latitude: 10.436528876010671, 
      longitude: -75.52775019109914,
      ref: 'Foto tomada de: Recetas gratis. https:\/\/www.recetasgratis.net\/receta-de-arroz-con-coco-colombiano-35552.html'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Mojarra frita',
      description: 'La gastronomía cartagenera, en su mayoría, se caracteriza por la presencia del mar en sus platillos. Por ende, la presencia de la mojarra en todos los menús no debe ponerse en duda. Traída de áfrica a la mesa costeña, la mojarra llegó en los años 50 al territorio (El Heraldo, 2019) un pez de escamas plateadas y carne blanca y jugosa,que fue parte de la dieta de los pueblos africanos e indígenas y, con la llegada de los colonizadores españoles, su preparación se fusionó con las técnicas culinarias europeas, dando origen a una receta única que cautivó paladares.\n\nPerfecto para un día de playa, la mojarra frita es un plato típico de la cocina colombiana. Este puede ser encontrado en la región de la costa caribe, ya que es un alimento que proviene del mar (pez de agua salada). Este plato se realiza hace siglos y es de masivo consumo debido a su exquisita preparación y acompañamientos como el arroz de coco, patacones y ensalada. \n',
      images: ['/assets/Mojarra frita.jpg'],
      latitude: 10.412359773451934, //\n\n10.436283056745825,
      longitude: -75.52540498980696, // -75.52731066141669'
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Mojarra frita',
      description: 'La gastronomía cartagenera, en su mayoría, se caracteriza por la presencia del mar en sus platillos. Por ende, la presencia de la mojarra en todos los menús no debe ponerse en duda. Traída de áfrica a la mesa costeña, la mojarra llegó en los años 50 al territorio (El Heraldo, 2019) un pez de escamas plateadas y carne blanca y jugosa,que fue parte de la dieta de los pueblos africanos e indígenas y, con la llegada de los colonizadores españoles, su preparación se fusionó con las técnicas culinarias europeas, dando origen a una receta única que cautivó paladares.\n\nPerfecto para un día de playa, la mojarra frita es un plato típico de la cocina colombiana. Este puede ser encontrado en la región de la costa caribe, ya que es un alimento que proviene del mar (pez de agua salada). Este plato se realiza hace siglos y es de masivo consumo debido a su exquisita preparación y acompañamientos como el arroz de coco, patacones y ensalada. \n',
      images: ['/assets/Mojarra frita.jpg'],
      latitude: 10.436283056745825,
      longitude: -75.52731066141669,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Salpicón de pescado',
      description: 'En la costa caribe colombiana la comida de mar es una parte fundamental de la identidad de sus habitantes y existen platos que fusionan los ingredientes locales con influencias de la cultura española. Uno de estos platos es el salpicón, cuyo origen se remonta a España.  Este plato tiene la característica de que se pueden utilizar diferentes tipos de pescado, como lo son: el pargo rojo, bagre salado, tilapia, entre otros. Para su preparación, se toma el pescado y una vez cocido en su totalidad se debe desbaratar; asimismo, se añade un guiso de tomate, cebolla, topito, ajo. Es importante usar aceite achiotado para mejorar el sabor y el agua de coco es indispensable para darle el toque de la costa (El Colombiano, 2022).',
      images: ['/assets/Salpicón de pescado.png'],
      latitude: 10.437251654161978, 
      longitude: -75.52754624113747,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Sancocho de pescado',
      description: 'Proveniente de \'sub-coctum\' (cocido a fuego lento), que se convierte en la cultura regional en sancocho, es uno de los platos típicos de la costa (Rojas, 2021). Se utiliza para revivir a los danzantes después de una noche de música y copas que fomenta la integración familiar y la amistad (Odette, 2012). Para prepararlo, se selecciona el mejor pescado, preferiblemente recién pescado, ya que cuanto más fresco mejor. Se cocina sobre leña para ser más. Se agregan ingredientes como mazorca, plátano verde y maduro, ñame, yuca, papa, ahuyama, zanahoria, cilantro, cebolla, tomates, apio y ajo y está listo (Rojas, 2021). El sancocho de pescado es el sabor del mar, de una vocación económica y la sazón afro. ',
      images: ['/assets/sancocho-pescado.jpeg'],
      latitude: 10.436507773332321, 
      longitude: -75.52783602278521,
      ref: 'Foto tomada de: https:\/\/co.pinterest.com\/pin\/68738149672\/'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Arroz de mariscos',
      description: 'Durante la época de la colonización española, el arroz llegó al Caribe y gracias al intercambio multicultural con los alimentos de la región, se hizo esta gran combinación para dar origen al arroz de mariscos y que, por supuesto, los ingredientes del territorio le dio un toque especial y que hoy en día se ha convertido en uno de los platos más apetecibles de la ciudad de Cartagena.Y por supuesto, qué mejor opción que acompañarlo con patacones y suero costeño, así que, no te quedes sin probar uno de los platos más deliciosos de la ciudad.',
      images: ['/assets/arroz-marinero.jpg'],
      latitude: 10.436528876010671, 
      longitude: -75.52775019109914,
      ref: 'Foto tomada de: Colombia.com . https:\/\/www.colombia.com\/gastronomia\/recetas-colombianas\/arroz-marinero-r648'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Arroz de camarones',
      description: 'Entre otras de las creaciones con animales del mar, se encuentra el arroz de camarones. Este plato es uno de los más tradicionales de la costa colombiana, preparado con arroz, (alimento de la tierra traído por los colonizadores españoles en el siglo XVI) y camarones (alimento del mar, del cual los indígenas que se encontraban en la costa caribe tenían gran conocimiento. En Colombia se consiguen los tropicales, los de río y los de agua fría). El arroz de camarones surgió como resultado de este intercambio culinario. Los españoles, familiarizados con la preparación del arroz en paella, encontraron en los camarones locales un ingrediente perfecto para combinarlo.\n\nA lo largo de los siglos, el arroz de camarones se convirtió en un plato representativo de Cartagena. Su presencia se hizo constante en las mesas de las familias cartageneras, especialmente en celebraciones y eventos especiales. Su sabor y aroma se asociaron con la identidad cultural de la ciudad, convirtiéndolo en un ícono gastronómico que trascendió fronteras. Hoy en día, el arroz de camarones sigue siendo un plato fundamental en la gastronomía cartagenera. Se prepara en restaurantes, mercados y hogares, conservando la esencia de su origen y transmitiendo su sabor de generación en generación.\n',
      images: ['/assets/Arroz de camarones.jpg'],
      latitude: 10.412359773451934, 
      longitude: -75.52540498980696,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Cazuela de mariscos',
      description: 'La cazuela de mariscos, refleja conexión de la región caribe con el mar. En su preparación, no existe una receta única, sino que cada región y familia aporta su toque especial, pero compartiendo la misma esencia: un guiso, variedad de mariscos frescos, como camarones, calamares, mejillones y pescado. Junto a la leche de coco, es ingrediente distintivo del Caribe colombiano el cual aporta un toque dulce y cremoso al plato. La cazuela se convirtió en una forma de aprovechar al máximo la abundancia que proporcionaba el mar.',
      images: ['/assets/Cazuela de mariscos.jpeg'],
      latitude: 10.436444465279221, 
      longitude: -75.52764290248962,
      ref: 'Foto tomada de : tqma, te quiero mejor alimentado https:\/\/pronacatqma.com\/recetas\/recipe\/7540-cazuela-de-mariscos.html'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Robalo frito',
      description: 'El pescado frito es un plato icono y exquisito de la gastronomía de la región caribe, se resalta por traer lo sabores auténticos del mar a una mesa y que se puede disfrutar en cualquier restaurante asi como en comida callejera (Films, s\/f). La preparación del pescado frito resulta sencilla: se lava el pescado, se sazona, se calienta el aceite y se frita por ambos lados para proporcionar la textura crujiente y cuidar su carne jugosa por dentro. En este caso, el robalo es uno de los preferidos por los comensales y chefs, no solo por su abundancia sino tambien por su alto contenido de proteínas, vitaminas, bajo en grasas, carne suave y un sabor que facilita cualquier tipo de sazón (El pescado frito, una delicia gastronómica costera – Restaurante bar el Muelle, s\/f). ',
      images: ['/assets/robalo-frito.jpeg'],
      latitude: 10.31966, 
      longitude: -75.58217,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Chicha de maíz',
      description: 'Bebida de maíz fermentada usada por las comunidades indígenas agrícolas del centro y el sur de América con fines rituales y, también, como alimento cotidiano. La chicha de maíz tiene su origen en las culturas precolombinas de los Andes colombianos. Los pueblos indígenas, como los muiscas y los taironas, cultivaban el maíz y lo utilizaban para preparar diversas bebidas y alimentos. Por lo que pasó a ser un símbolo de identidad cultural. Con la llegada de los españoles al territorio y sus distintas formas de elaboración de bebidas fermentadas, como la cerveza y el vino, la tradicional bebida experimentó variaciones. Esta famosa bebida llegó a Cartagena gracias al intercambio cultural, siendo un gran puerto comercial. Se convirtió en una bebida popular por su bajo costo.',
      images: ['/assets/Chicha de maíz.jpg'],
      latitude: 10.427947759671707, 
      longitude: -75.54836023989515,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Chicha de arroz',
      description: 'La Chicha de Arroz, se elabora de forma sencilla pero que requiere paciencia y atención al detalle. En Cartagena, el arroz se hierve hasta que esté tierno, se mezcla con agua, azúcar y canela, y se deja fermentar durante varias horas o días, dependiendo del gusto. En algunas ocasiones, se le agrega piña para darle un sabor más intenso. La Chicha no solo es deliciosa, sino también un símbolo de la resistencia cultural de los pueblos indígenas ya que lograron adaptar sus costumbres ancestrales con los nuevos ingredientes que llegaron al continente. A pesar de la colonización y la adopción de nuevas costumbres, la Chicha ha conservado su esencia y sigue siendo parte importante de la identidad colombiana. ',
      latitude: 10.427947759671707,
      longitude: -75.54836023989515,
      images: ['/assets/Chicha de arroz .jpeg'],
      ref: 'Foto tomada de :  ENRI LEMOINE https:\/\/enrilemoine.com\/2023\/04\/05\/receta-de-chicha-de-arroz-venezolana\/'
     },
     
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Bollo de maíz',
      description: 'Quizás uno de los alimentos más antiguos de la región caribe, nacido de la sazón indígena y su vivencia para conservar los alimentos por largo tiempo. El bollo de maíz en todas sus variaciones se volvió un infaltable en la región para los desayunos costeños, y sobre todo con el famoso “matrimonio” bollo con un buen “pedazo de queso”. Además, el bollo es popular en las tradiciones gastronómicas y económicas de las familias populares gracias a su versatilidad y bajo costo de fabricación, cuenta la matrona Valeriana: “Yo aprendí a hacer bollo viendo a mi mamá, ella los hacía para vender y mientras fui creciendo me ponían tareas, lavaba el maíz, picaba, molía, amasaba y luego ayudaba a vender, esto hace parte de nuestra tradición” (Bovea, 2023). ',
      images: ['/assets/bollo.png'],
      latitude: 10.423572170026668, 
      longitude: -75.55022189152659,
      ref: 'Foto tomada de: https:\/\/boquisabroso.com.co\/aperitivos\/bollo-de-mazorca\/'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Bollo de coco',
      description: 'Para acompañar tu desayuno, el bollo de coco es una excelente opción. Es un alimento a base de maíz cocido envuelto en hojas de mazorca lo que nos remonta a su origen indígena (Ana Pájaro, 2018). Sin embargo, la adición de este fruto tropical aporta un sabor más apetecible a este maravilloso plato, y por qué no acompañarlo con queso y suero costeño, indudablemente es un plato típico de la ciudad que no te puedes perder. ',
      images: ['/assets/Bollo de coco.png'],
      latitude: 10.395791580566748, 
      longitude: -75.4766274757554,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Coctel de camarones ',
      description: 'En la vitrina gastronómica de Cartagena por excelencia, no podía faltar el coctel de camarón. Se cree que el coctel de camarones tiene sus raíces en las comunidades afroantillanas que habitaban las islas del Caribe. Estas comunidades, expertas en la pesca y la cocina, preparaban platos frescos con camarones, sazonados con especias, aprovechando el alimento del mar. Este es un plato culinario insignia del Perú, que llegó a Colombia por intercambio cultural entre todo el continente y evolucionó con ingredientes introducidos por los españoles como el tomate, la cebolla y el cilantro. Tomó fuerza en Cartagena en 1953 gracias a Manuel Cárdenas De Ávila (alias Sincelejo), un reconocido coctelero (fallecido en 2010) que conquistaba los corazones de oriundos y turistas con sus cocteles “afrodisiacos” (Parra, J. 2013). Actualmente, el coctel de camarones es un símbolo de la cultura popular cartagenera, que toma fuerzas en épocas de Semana Santa. En 2015, Colombia ganó el Récord Guinness por el mayor cóctel de camarón del mundo, el cual fue hecho en Cartagena y pesó 1.320 kilos  (El Espectador, 2015).',
      images: ['/assets/Coctel de camarones.jpg'],
      latitude: 10.412359773451934, 
      longitude: -75.52540498980696,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Fogón Cartagenero',
      line: 'Típico',
      name: 'Sancocho',
      description: 'El sancocho, más que un simple plato, es una oda a la cocina colombiana, un festín familiar que reúne sabores y tradiciones. Considerado un plato reconfortante, el sancocho tiene el poder de unir a las familias alrededor de la mesa, creando momentos memorables que se transmiten de generación en generación. Cindy Quintana, como muchos colombianos, guarda en su memoria los aromas y sabores del sancocho de su abuela. Desde pequeña, recuerda los fines de semana en su casa, donde el sancocho se convertía en el plato principal (Mujeres, tradición y sazon, 2018). Observaba con fascinación la preparación del sancocho, un proceso meticuloso que involucraba la selección de ingredientes frescos, la cocción a fuego lento y el toque de la sazón familiar. El sancocho, en su esencia, es un caldo sustancioso que combina diferentes carnes, verduras y tubérculos. ',
      images: ['/assets/Sancocho.png'],
      latitude: 10.43710920946364,
      longitude: -75.5275892539699,
      ref: '-Foto tomada de: Twitter https:\/\/twitter.com\/rest_picatierra\/status\/1064158055133265921'
     },
     {
     category: 'Patrimonio Inmaterial',
     subcategory: 'Tradición Oral y Danzas',
     name: 'Champeta',
     description: 'La Champeta es un género musical diverso que encuentra sus raíces en la fusión de influencias africanas y afro caribeñas. Desde el continente africano se encuentran ritmos contagiosos como la Rumba Congolesa, el Soukous, el Highlife, el Juju, el Afrobeat, el Chiremerera, el Benga y el Mbaqanga, provenientes de países como la República Democrática del Congo, Ghana, Nigeria, entre otros países de África. La Champeta también se nutre de ritmos afrocaribeños como el Son, Guaguanco, Bolero, Soca, Calypso, Ska, Reggae, Kompa, Merengue y Bachata, procedentes de Cuba, Puerto Rico, y demás países del Caribe Americano. Estos ritmos se entrelazan con bailes y tradiciones afro del Caribe colombiano como el Bullerengue, Son de negros, Tambora y Mapalé, dando lugar a una mezcla de sonidos y movimientos que definen a la Champeta (Escallón, R., 2024, p. 7).\n\nAntes de convertirse en el género musical que conocemos hoy, era una cultura marcada por la estigmatización, arraigada en la pobreza y marginalidad. Sin embargo, en la actualidad se le reconoce como patrimonio nacional ya que esta fusión cultural celebra la diversidad que nos enriquece. A lo largo del tiempo, la Champeta ha evolucionado y ganado popularidad en toda Colombia y otros países de América Latina, convirtiéndose no solo en música, sino también en un estilo de vida que se refleja en la forma de vestir, el lenguaje y la danza (Escallón, R., 2024, p. 8).\n',
     images: ['/assets/Champeta.png'],
     line: '',
     places: 'Museo de la Champeta, Barrio Olaya',
     latitude: 10.42562751034854,
     longitude: -75.54850644838004,
     ref: ''
    },

    {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      line: '',
      name: 'Bullerengue',
      description: 'Inspirado por el lumbalú, el bullerengue es cultivado principalmente como un ritmo cantado por mujeres, acompañadas por dos tambores: el llamador y el alegre. La estructura de su lírica emana de cantos y responsos que abren paso a las improvisaciones en medio del jolgorio (Sierra, 2010). Existen, a su vez, tres tipos de bullerengue: 1-Bullerengue asentao: También conocido como bullerengue antiguo, tiene raíces en África que aún perviven en las voces de mujeres octogenarias (Sierra, 2010). Se caracteriza por ser un ritmo lento y pausado, donde las cantadoras se sientan en el suelo mientras entonan coplas largas y poéticas que narran historias de la vida cotidiana, el amor, la muerte y la espiritualidad. 2-La chalupa: Se caracteriza por ser un ritmo más vivo y festivo, sin enfado alguno. Las cantoras se paran y, al son de los tambores, bailan y entonan coplas cortas y humorísticas. 3-Fandango "e lenguas: Es el ritmo más vivo, complejo y acrobático del bullerengue. En este, las cantadoras se enfrentan en un duelo verbal donde, al son de tambores vibrantes, improvisan coplas desafiándose mutuamente con rimas y juegos de palabras (García, 2016). En este sentido, el bullerengue es un canto a la vida de la mujer negra, a sus desafíos, dolores, sentires, rebeldía y temple como mujer. Una de las mayores exponentes a nivel mundial del bullerengue es la maestra Petrona Martínez.',
      images: ['/assets/bullerengue.jpg'],
      latitude: 10.10465935845067, 
      longitude: -75.20069863072726,
      ref: 'Foto tomada de: https:\/\/www.revistacredencial.com\/historia\/temas\/el-ritual-del-bullerengue'
     },
    {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'Changüí',
      line: '',
      description: 'Remontado al vivir de los campesinos, del campo y del fuego plebeyo el ritmo musical changüí originado en cuba y que se estaciona en Cartagena se considera la madre del son cubano y del sexteto palenquero (Medina, 2011). Sus ritmos son, danzón, charanga y guaguancó (Escallón, 2024) dan vida a las festividades y danzas de los palenqueros que se alegran al sonar de la marimbula, el bongo y las maracas. ',
      images: ['/assets/changui.jpg'],
      latitude: 10.10465935845067, 
      longitude:-75.20089863072726,                                                                                                                                                                                                                                                                                                                         //ongo  Museo de la champeta: 10.42562751034854, -75.54850644838004',
      ref: 'Foto tomada de:https:\/\/www.telesurtv.net\/telesuragenda\/cuba-llego-changui-patrimonio-cultural-Inmaterial-20210426-0003.html'
    },
    {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'El Garabato',
      line: '',
      description: 'En el contexto de la opresión vivida en Cartagena de Indias, surge la Danza del Garabato, inicialmente conocida como Danza de la Vida y la Muerte. Esta expresión cultural, proveniente del pueblo afrodescendiente, se caracteriza por movimientos corporales al son de los tambores, con los que la persona negra (afrodescendiente) expresaba sus sentimientos. En ella se representa la lucha entre la vida y la muerte en donde, después del enfrentamiento, triunfa la muerte (Orozco et al., s.f.). Esta danza mágica y trágica es famosa en Bocachica.',
      images: ['/assets/El Garabato.jpg'],
      latitude: 10.3256922, 
      longitude: -75.5787999,
      ref: ''
    },
    {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'La danza de los diablos espejo',
      line: '',
      description: 'La Danza de los Diablos Espejo, refleja la identidad cultural de las comunidades del caribe. Con sus coloridos trajes y movimientos enérgicos, esta danza contagia de entusiasmo a quienes  lo bailan y lo ven convirtiéndose en un elemento importante de las Fiestas de la Independencia y los Carnavales. Los bailarines, vestidos con bombachos rojos, medias negras, faldas de pañuelos y máscaras diabólicas adornadas con espejos y mayas, se transforman en diablos que recorren las calles al son del tambor y la caja. La leyenda detrás de la Danza de los Diablos Espejo se remonta al siglo XIX,  cuando un hombre de la isla de San Miguel, en el Archipiélago de las Perlas, llegó en busca de fortuna durante la época del caucho. En Corpus Christi, movido por una manda de por vida, se disfrazó con hojas secas de plátano y una máscara improvisada, y comenzó a bailar por las calles del pueblo. Su entusiasmo y energía contagiaron a los habitantes, quienes, encantados por la danza, le pidieron que les enseñara. Así, desde ese entonces, la Danza de los Diablos Espejo se convirtió en una parte integral de las festividades (Diablos Espejos, Bunde y Bullerengue, las Danzas de Garachiné, 2024)',
      images: ['/assets/La danza.jpeg'],
      latitude: 10.32527, 
      longitude: -75.57822,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'Lumbalu',
      description: 'Traída de una tradición Congo-angola y gestada con música, una lengua única y desde la espiritualidad nace el denominado lumbalú (Sierra, 2010). Se designa este nombre a las ceremonias funerarias producto de la muerte de los adultos que en vida vivieron en el cabildo de palenque (Escalante, 1989). El termino hace apología al tambor principal funerario principal utilizado para marcar los tiempos de los canticos y las danzas. En ese sentido, el lumbalú más que ser un ritual funerario es la representación de una memoria, una identidad y a una cultura pura. ',
      line: '',
      images: ['/assets/lumbalu.jpg'],
      latitude: 10.10465935845067, 
      longitude: -75.20059863072726,
      ref: 'Foto tomada de: https:\/\/elcomejen.com\/2020\/12\/18\/lumbalu-o-canto-a-los-muertos-entranamientos-de-la-espiritualidad-palenquera\/'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'Sexteto ',
      line: '',
      description: 'Se define como un formato musical compuesto por seis instrumentos. En el caso del sexteto o son palenquero, los instrumentos utilizados son la marímbula, guacharaca, llamador, alegre, maracas y claves (Escallón, 2024). Este ritmo llegó de Cuba en la década de 1920 y se expandió a los municipios de la costa caribe. Con su influencia negra y mestiza, se realizaron variaciones al ritmo para adaptar una nueva identidad a través del formato musical, convirtiéndolo en una expresión negra y mestiza de origen cubano. El juglar palenquero Rafael Cassiani menciona que los sextetos eran una forma de disfrutar la vida durante los momentos de recreación, descanso y goce (Escallón, 2024). Posteriormente, fue uno los formatos musicales que permitió gestar la champeta. ',
      images: ['/assets/sexteto.jpg'],
      latitude: 10.10465935845067, 
      longitude: -75.20019863072726,
      ref: 'Foto tomada de: https:\/\/es.wikipedia.org\/wiki\/Sexteto_Habanero'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Tradición Oral y Danzas',
      name: 'El pavo con la pava',
      description: '“Yo tengo una pava hinchada con huevos de codorniz. Si la pava no me quiere, si la pava no me quiere, cojo el camino y me voy", cantan en coro, mientras se hace una danza erótica entre bailarines y bailarinas” (Salazar, 2007). La danza del pavo con la pava, tradicional de la tierra de San Basilio de Palenque, es uno de los bailes característicos de los ritos fúnebres, se basa en un juego de ronda realizado en los novenarios.',
      line: '',
      images: ['/assets/El pavo con la pava.jpg'],
      latitude: 10.10363765529243, 
      longitude: -75.1990892711642,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: '⁠Festival de las maracas',
      description: 'El Festival Artesanal y Cultural de las Maracas se lleva a cabo cada año en el marco de las fiestas patronales en honor a San Isidro Labrador, en el corregimiento de Pontezuela, Cartagena. En este evento los artesanos del corregimiento ponen a disposición de la comunidad su conocimiento y talento, expresando la cultura, tradición y herencia de su región a través del fruto del árbol del totumo, un Material arraigado en su identidad durante años (De La Cruz, A., 2013).\n\nPara la elaboración de las maracas se toma el fruto del totumo, una vez extraída la pulpa y secado el fruto, se le introducen semillas de chuira y se finaliza con la adición de manubrios de madera (Artesanías de Colombia., s.f). Las fiestas de San Isidro Labrador se celebran en fechas cercanas al 15 de mayo, sin embargo, se recomienda verificar esta información antes de asistir. ',
      line: '',
      images: ['/assets/Festival de las Maracas.png'],
      latitude: 10.552270061630098, 
      longitude: -75.46764927751832,
      ref: '', 

     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: 'Festival del frito',
      description: 'El festival del frito Cartagenero es una celebración gastronómica anual en el marco de las Fiestas de la Virgen de la Candelaria. Este festival lleva una tradición de mas de 35 años, el evento destaca las tradiciones culinarias afrocolombianas y ha promovido la herencia cultural y el papel de las mujeres en la preservación de los saberes ancestrales y las tradiciones de generación en generación (Theram, 2024). El festival del frito es la memoria de la interculturalidad y el desarrollo de una región de la mano con la comida. En 2024, el festival fue total éxito, con ventas que superaron los $700 millones y más de 105 mil arepas de huevo consumidas durante los 10 días del evento. Chambacú fue la sede, atrayendo a 120 mil personas diarias, la mayor asistencia en la historia del festival (Theram, 2024 según cifras del IPCC, 2024). ',
      line: '',
      images: ['/assets/Festival del pastel Cartagenero.jpg'],
      latitude: 10.392682467873914,
      longitude: -75.46141917289185,
      ref: 'Foto tomada de: https:\/\/www.eluniversal.com.co\/cultural\/la-toxica-la-arrebata-y-otros-fritos-innovadores-del-festifrito-2024-NJ9874843'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: 'Festival del dulce cartagenero',
      description: 'Si quieres hacer parte de unos de los eventos más sabrosos de la ciudad, sin duda, asistir al Festival del Dulce es uno de los atractivos que no te puedes perder. \nSe celebra solo una vez al año y nace como un homenaje a las tradiciones católicas de la Semana Santa, por lo que comienza el Domingo de Ramos y finaliza Domingo de Resurrección. Se ha  convertido en una gran oportunidad para que los turistas puedan conocer más sobre la cultura e historia de Cartagena a través de los manjares que hacen parte de la identidad, cultura y tradición de la ciudad (Nueva Lengua, 2023).\nEs la ocasión perfecta para encontrar todos esos dulces típicos y tradicionales, desde el dulce de corozo para aquellos amantes del ácido, hasta los que prefieren algo más dulzón como la cocada; o porque no probar esos sabores peculiares como el ñame. Sin duda alguna, para cada paladar hay un dulce perfecto.',
      images: ['/assets/festival-dulce-1.jpg', '/assets/festival-dulce-2.jpg', '/assets/festival-dulce-3.jpg'],
      line: '',
      latitude: 10.422407381638118, 
      longitude: -75.55024830273896,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: 'Festival del pastel cartagenero',
      description: 'El Festival del Pastel Cartagenero es un evento gastronómico que se celebra anualmente en Cartagena de Indias. El Instituto de Patrimonio y Cultura de Cartagena se encarga de organizar una agenda para salvaguardar dicha tradición. Ahora bien, en el festival se pueden encontrar una gran variedad de pasteles cartageneros, elaborados con diferentes tipos de carne, pescado y verduras. También hay música en vivo, bailes tradicionales y otras actividades culturales. Cabe resaltar que este festival tiene como objetivo “integrar a la comunidad en los procesos de preparación de los deliciosos pasteles y transmitir los saberes ancestrales representados en la culinaria popular” (Alcaldía Mayor de Cartagena de Indias, 2023).  Se recomienda tener muy en cuenta las fechas en las que se realiza el festival, así como el lugar. Ya que estos pueden variar año tras año. De igual manera, es importante revisar los precios estandarizados por la alcaldía para la venta de los pasteles.\n',
      images: ['/assets/Festival del pastel Cartagenero.jpg'],
      line: '',
      latitude: 10.42284112223397, 
      longitude: -75.54730369110453,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: 'Fiestas de la independencia de Cartagena',
      description: 'Las Fiestas de la Independencia de Cartagena son una celebración anual que conmemora la declaración de independencia de la ciudad del dominio español en 1811. Se celebra con desfiles, música, bailes tradicionales, gastronomía y diversas actividades culturales que son la demostración del carácter del pueblo cartagenero. Es una ocasión para resaltar la rica historia y diversidad cultural de Cartagena, y para honrar a los héroes que lucharon por la libertad de la ciudad. Las fiestas son más que una simple diversión, son una conmemoración a los ancestros cartageneros por el acto de valentía que cambio la historia. Es un momento para reflexionar sobre la importancia de la libertad, la unidad y la identidad cultural.',
      line: '',
      images: ['/assets/Fiestas de independencia de cartagena.jpeg'],
      latitude: 10.440011955611258, 
      longitude: -75.52117838899719,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Festivales',
      name: 'Festival de bandas',
      description: 'El Festival Departamental de Bandas en Bolívar tendrá su décimo segunda versión en este año. Las bandas, en las categorías de mayor y menor, se presentan año a año para obtener el título de las mejores bandas del departamento, y al mismo tiempo, brindarle a la ciudad de Cartagena días llenos de alegría, felicidad y mucha música. \n\nEn este festival son muy comunes el porro y el fandango, ritmos que revelan la identidad cultural y la tradición oral de un departamento formado por el intercambio de culturas. Es un punto donde las identidades culturales se unen para sacar a flote los ritmos de los bolivarenses, teniendo mucha importancia para su identidad. \n\nEl último festival se realizó en el parque Lácides Segovia del barrio manga, se recomienda verificar información.',
      images: ['/assets/Festival de bandas cartagena.jpg'],
      line: '',
      latitude: 10.411896196615082, 
      longitude: -75.53455119214634,
      ref: ''

     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Medicina Tradicional',
      name: 'Rezos y protecciones palenqueras',
      description: 'En San Basilio de Palenque se encuentra Rosalina Cañate Pardo, rezandera y santiguadora   de la cultura ancestral palenquera. Si el turista busca una medicina alternativa a la convencional, desde luego, visitar a Rosalina será toda una experiencia. \nRosalina heredó todos sus conocimientos, todos sus saberes de sus pares y de su madre, que también eran unos representantes de la medicina,  de las curativas palenqueras a través de las plantas, de las hierbas, de las herbolarias medicinales,  de las oraciones mágico-religiosas encarnadas en los Orisha  y en los dioses católicos, en ese sincretismo  presente en la cultura palenquera. \nEn el año 2017 en el Festival de Tambores y Expresiones Culturales, se realizó un homenaje a Rosalina, por esa sabiduría que ha salvaguardado y que está presente en ella, y que es extensiva a palenqueros, niños, mujeres y personas de fuera, que acuden a ella para hacerse rezos antiguos, componendas de cuerpos,  a cada uno de los artes y de la sabiduría  que están presentes en la rezandería, la medicina tradicional, en esto de las curativas ancestrales en Palenque. ',
      images: ['/assets/rezos (1).jpg', '/assets/rezos (2).jpg', '/assets/rezos (3).jpg'],
      line: '',
      latitude: 10.103905, 
      longitude: -75.201228,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Medicina Tradicional',
      name: 'Hierbas tradicionales sabedoras',
      description: 'Mi abuela no pierde la tradición, incluso con la medicina, ella dice que los médicos matan con tanta pastilla. En la casa siempre prefieren utilizar poderosas plantas como la zarzaparrilla, el diente de león, la acacia de india. Hace algunos años a Yola le salieron unas peloticas en el bajo vientre, fue a un médico alopático y le diagnosticaron cáncer. Un día estando ella en su casa, pensativa con tan nefasta noticia, llegó un indio que le dijo que eso que tenía era una mala energía, que debía hacer algo pronto o iba a morir. Cuando este señor se fue, el perrito que teníamos brincó y cayó muerto. Decidió ir a una casa espiritual en la Boquilla donde el popular espíritu del médico José Gregorio la curó. Cuando fue a consulta, ya no tenía nada. De todas formas toca ir al doctor siempre, pero es verdad que no hay una sola forma de curar. \nCindy Quintana” (Mujeres, tradición y sazón, 2018)\n',
      images: ['/assets/Hierbas tradicionales sabedoras.jpg'],
      line: '',
      latitude: 10.43633581348272, 
      longitude: -75.52731024127098,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: '⁠El pechiche',
      description: 'El pechiche mide aproximadamente 2 metros de largo por 40 centímetros de diámetro en el aro que sostiene el parche de cuero de chivo o cabro. La boca inferior, abierta, mide alrededor de 25 centímetros. Esto lo convierte en un tambor muy grande de una sola membrana con fondo abierto. Para tocarlo, se coloca en una horqueta de apoyo, y el ejecutante se monta sobre el tambor y lo golpea con mazos (Fundación Bat). Este tambor es característico de fiestas, rituales y ceremonias de los muertos en el lumbalú de Palenque (Roa, 2019). Se menciona “que el parche de membrana está hecho de cuero de venado saíno y recubre la boca de mayor tamaño. El parche está reforzado con un aro de bejuco del cual salen cuerdas gruesas en forma de V o W, llamadas llaves, que van a un cinturón también de bejuco. Este cinturón encierra las cuñas adosadas para producir el temple o tensión” (Fundación Bat, s\/f). Para ejecutarlo, se usan las manos abiertas golpeando la membrana. Solo pueden tocarlo personas que dominan los toques y tienen categoría ceremonial, conocida como la fiesta de Batá. Existe la creencia palenquera de que este tambor solo puede ser interpretado durante el lumbalú, ya que, si se ejecuta fuera de estas ceremonias, puede acarrear la muerte de alguna de las personas presentes durante la interpretación (Fundación Bat, s\/f). ',
      images: ['/assets/pechiche.jpg'],
      line: '',
      latitude: 10.32527,
      longitude: -75.57822,
      ref: 'Foto tomada de: https:\/\/www.fundacionbat.com.co\/instrumentos.php?IDDepartamento=23'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: '⁠La timba',
      description: 'La timba es un tambor, un instrumento de herencia africana, fundamental en la música popular de Cartagena. Fabricado en madera y piel de res, es fundamental en diversos géneros musicales, como el cumbé, la champeta, el lumbalú y el bullerengue, el tambor timba es esencial en las celebraciones populares. La timba es un patrimonio cultural que representa la resistencia, alegría y creatividad del pueblo cartagenero.',
      images: ['/assets/La timba.jpg'],
      line: '',
      latitude: 10.11420, 
      longitude: -75.19490,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: 'La tambora, bombo',
      description: 'La tambora es un sentimiento que se transmite a través del lenguaje corporal. (Bendack Castro, D. M. 2016). \nEs una expresión cultural de Colombia pero sus raíces se remontan a África, donde los ancestros la utilizaban para transmitir historias y mensajes a través del ritmo. Al llegar a las tierras colombianas, la tambora se adaptó a la región, dando origen a diferentes variantes, siendo el bombo la más conocida y adoptada por las comunidades afrocolombianas. A diferencia del bombo, que solo se toca de un lado, la tambora colombiana se golpea por ambos lados, creando un ritmo más complejo y dinámico. Se ha convertido en un pilar fundamental de la música tradicional colombiana, especialmente en géneros como la cumbia y el vallenato. Más allá de un instrumento musical, la tambora es un símbolo de identidad y el toque Colombiano en al historia.\n\n',
      images: ['/assets/Tambora.jpeg'],
      latitude: 10.32627, 
      longitude: -75.57822,
      line: '',
      ref: 'Foto topmada de : https:\/\/www.radionacional.co\/cultura\/asi-suenan-los-aires-ancestrales-del-chande-el-berroche-la-tambora-tambora-y-la-guacherna'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: 'El llamador',
      description: 'El llamador es un instrumento de percusión de origen africano, utilizado en la música tradicional del Caribe colombiano. Su función es marcar y llevar el tiempo. Junto con la marímbula, la clave, la guacharaca y el tambor alegre, compone el conjunto de música tradicional de San Basilio de Palenque. Tradicionalmente, se fabrica con madera de caracolí para el cuerpo, cuero de chivo para la superficie superior, madera de saúco para las estacas laterales y fibra de maguey para las cuerdas (Sindamanoy., 2019).',
      images: ['/assets/Llamador.png'],
      line: '',
      latitude: 10.11320, 
      longitude: -75.19490,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: '⁠El alegre',
      description: 'Es un tambor de forma cónica, con una membrana en su parte superior que se asegura con un aro hecho de bejuco, al cual se le entrelaza una cabuya de fique o un lazo, que va atado en la parte inferior del cono a un cinturón, que a su vez es asegurado con cuñas de madera colocadas alrededor. Todo este sistema con el fin de tensionar el cuero. El cono en la parte inferior se deja abierto. Su forma de tocarlo es con las palmas de las manos directamente sobre el cuero, que puede ser de becerro, caimán, piel de venado o piel de cabra (Fundación Bat, s\/f). El tambor alegre es un icono para todos los ritmos propios de la región caribe llámese bullerengue, fandango, cumbia, porro, mapalé o gaitas siendo asi el alegre el tambor que crea lenguajes de sonidos que se mezcla con las identidades caribeñas. ',
      images: ['/assets/alegre.jpg'],
      line: '',
      latitude: 10.32827, 
      longitude: -75.57822,
      ref: 'Foto tomada de: https:\/\/www.diccionariodecolombia.expert\/diccionario-enciclopedico\/alegre\/'
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: 'La marímbula',
      description: ' A tan solo una hora de Cartagena descubrirás un tesoro cultural:San Basilio de Palenque, el primer pueblo libre de América. Cuna cultural, ancestral, musical y gastronómica. \nAllí tendrás la oportunidad de deleitarte con sonidos africanos como la marímbula, el cual es un instrumento musical del complejo cultural bantú, procedente de África, concretamente de Congo y Angola, llega al Caribe dentro de un amplio proceso de intercambio interétnico, en el cual se\narticula con los formatos tradicionales de la música regional costeña (Enrique Luis Muñoz Vélez, s.f.). Es un instrumento de percusión típico de los grupos musicales de la comunidad palenquera como el Sexteto Tabalá.\nSi tienes la fortuna de visitar San Basilio de Palenque del 14 al 17 de octubre podrás ser partícipe del Festival de Tambores y Manifestaciones Culturales en San Basilio, y de esta manera, encantarse con los distintos sonidos africanos y apreciar las presentaciones de los grupos musicales más importantes del corregimiento. ',
      images: ['/assets/marimbula (1).jpeg', '/assets/marimbula (1).jpg', '/assets/marimbula (2).jpg'],
      line: '',
      latitude: 10.103591185916724, 
      longitude: -75.19952292409107,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: 'La clave',
      description: 'La clave, un instrumento de percusión menor originario de África, ha jugado un papel fundamental en la música popular de Cartagena desde la época colonial. Su sonido seco y agudo, producido al golpear dos piezas de madera, sirve como base rítmica en diversos géneros musicales, como el fandango, la champeta y la salsa.',
      images: ['/assets/La clave.jpg'],
      line: '',
      latitude: 10.11320, 
      longitude: -75.19490,
      ref: ''
     },
     {
      category: 'Patrimonio Inmaterial',
      subcategory: 'Artesanias',
      name: 'La guacharaca',
      description: 'Es un instrumento musical ide golpe raspado, es un instrumento fundamental en la música vallenata. A pesar de su apariencia sencilla y materiales humildes, la guacharaca emite un sonido característico que le da ritmo y sabor a este género musical. Su elaboración suele hacerse con caña o lata. La guacharaca se compone de dos partes: la guacharaca en sí, que tiene una superficie corrugada, y el peine o trinche, hecho de alambre duro y mango de madera, que se utiliza para rascar la superficie corrugada. ',
      images: ['/assets/La guacharaca.jpeg'],
      line: '',
      latitude: 10.32527, 
      longitude: -75.57822,
      ref: 'Foto tomada de : El pilon https:\/\/elpilon.com.co\/rafa-guacharaca-amante-del-folclor\/'
     },
     {
        category: 'Patrimonio Natural',
        subcategory: 'De Naturaleza',
        name: 'Parque Nacional Natural Corales del Rosario de San Bernardo',
        description: 'Ubicado en el departamento de Bolívar, cerca de Cartagena, el Parque Nacional Natural Corales del Rosario y de San Bernardo está llena de biodiversidad marina y terrestre. Este lugar alberga una amplia gama de ecosistemas, incluyendo manglares, arrecifes coralinos y praderas marinas. Los arrecifes coralinos, en particular, son de vital importancia, ya que actúan como barreras naturales que protegen la línea costera y albergan mucha diversidad de especies. De hecho, este parque alberga la plataforma coralina más extensa y con mayor diversidad y desarrollo de Colombia. Más allá de su valor ecológico, el Parque Nacional Natural Corales del Rosario y de San Bernardo también tiene una gran importancia social y económica para las comunidades locales. El turismo sostenible y la pesca responsable son actividades que generan empleo para los habitantes de la región.',
        line: '',
        images: ['/assets/corales del rosario.jpeg'],
        latitude: 9.792953077154035, 
        longitude:-75.84295024401273,
        ref: 'Foto tomada de : Colombia.com\nhttps:\/\/www.colombia.com\/turismo\/sitios-turisticos\/cartagena\/atractivos-turisticos\/sdi463\/72530\/parque-Natural-corales-del-rosario-y-san-bernardo'
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'De Naturaleza',
        name: 'La laguna encantada',
        description: 'La Laguna Encantada se encuentra ubicada en las Islas del Rosario, parte del archipiélago de Cartagena de Indias. Recibe su nombre debido a la presencia de bioluminiscencia en las noches oscuras, un fenómeno mágico que se puede observar en pocos lugares del mundo.\n\nPara llegar a La Laguna Encantada se utiliza comúnmente lancha, catamarán, entre otras embarcaciones. La Laguna cuenta con mucho plancton y está rodeada de manglar, por lo que estas condiciones lo convierten en uno de los pocos espacios que permiten al ser humano contemplar el plancton luminoso (Goez, A., 2019).\n',
        line: '',
        images: ['/assets/laguna-encantada.jpg'],
        latitude: 10.180250638964814,
        longitude: -75.72724046057765,
        ref: ''
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'De Naturaleza',
        name: 'Parque temático Vivarium del Caribe',
        description: 'El parque temático vivarium es un destino ubicado a tan solo unos minutos de Cartagena entre los municipios de bayunca y pontezuela. El parque esta dedicado a la recreación, educación y conservación de la fauna del bosque seco y humedales del caribe colombiano. Los visitantes que llegan al parque tendrán la oportunidad de observar especies de reptiles, peces y anfibios representativos de la identidad regional, a su vez, se encuentran animales exóticos decomisados por las autoridades encargadas por tráfico de fauna (Cartagena, 2020). Entre ellos se encuentran cocodrilos, caimanes, serpientes, tortugas y peces de distintos orígenes hidrográficos. Por otro lado, el parque busca que los turistas se adentren a conocer las historias de las especies, sus cuidados y su importancia en los ecosistemas permitiéndoles interactuar con ellas como puede ser tener contactos con serpientes (Cartagena, 2020)',
        line: '',
        images: ['/assets/vivarium.jpg'],
        latitude: 10.539842650395576,
        longitude: -75.41794904791125,
        ref: 'Foto tomada de: https:\/\/cartagenatopexperiences.com\/vivarium-del-caribe\/'
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'De Naturaleza',
        name: 'Orika',
        description: 'Orika, ubicado en Isla Grande, hace parte del archipiélago Islas del Rosario. Como parte del parque Natural, la protección ambiental del mar y el territorio es una de las tareas más valiosas de la comunidad de Orika (El País, 2022) y es por esto, que se convierte en una de las mejores opciones para aquellos amantes de la naturaleza, que buscan apoyar un turismo alternativo como lo presenta la comunidad de Orika, y lo más importante, amigable con el medio ambiente.\nLa comunidad de Orika, un grupo de afrodescendientes nativos, han cambiado su concepción y costumbres para valorar y preservar la zona ecológica del Bosque Seco Tropical y la Zona de los Manglares. En Orika encontrarás una diversa oferta que va desde visitar el Museo de la Memoria Viva donde podrás recorrerlo y conocer la historia de la comunidad, sus prácticas y saberes tradicionales (Consejo Comunitario Afrodescendiente). Mientras que para los amantes del mar hay una variedad de opciones desde sumergirse en sus espléndidas aguas ya sea del mar o las lagunas internas que tiene la Isla, o para aquellos más aventureros, explorar los túneles del manglar y hacer avistamiento de aves; y para lo más arriesgados, atreverse a adentrarse en el mar y descubrir una avioneta sumergida, convertida hoy en día en un refugio de peces.\nSu compromiso con el medio ambiente es destacable y es que los alojamientos que ofrece la comunidad tienen plantas solares y de esta manera abastecen las energía de los Eco-hoteles, y es por esta razón que a pesar de que no cuentan con aire acondicionado, el diseño arquitectónico se basa en la máxima circulación del aire interior de las habitaciones (Awake, s.f.)\nNo cabe duda de lo sorprendente que es Orika. Su compromiso con la conservación ambiental, su cultura y su gran oferta turística responsable se convierte en un imperdible cuando visites la ciudad de Cartagena. ',
        line: '',
        images: ['/assets/orika (1).jpg', '/assets/orika (1).png', '/assets/orika (2).jpg', '/assets/orika (2).png'],
        latitude: 10.177248835461361,
        longitude: -75.74228598236944,
        ref: ''
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'De Naturaleza',
        name: 'Volcán del totumo',
        description: 'A pesar de su nombre, este no es un volcán tradicional, sino un cono de lodo que se ha convertido en un popular destino turístico, para sumergirse en su lodo rico en minerales, conocido por sus propiedades beneficiosas para la piel. La leyenda local cuenta que hace muchos años, el Volcán del Totumo era un volcán activo, pero un sacerdote lo domó lanzando agua bendita sobre su lava, transformándola en el lodo terapéutico que hoy conocemos. La experiencia en el Volcán del Totumo no termina con el baño de barro. Los  turistas pueden continuar su recorrido sumergiéndose en la Ciénaga del Totumo, una laguna de agua dulce ubicada a pocos pasos del volcán. ',
        line: '',
        images: ['/assets/totumo.jpg'],
        latitude: 10.745019748667286, 
        longitude: -75.24118849209347,
        ref: 'Foto tomada de : El volcán del Totumo - Cartagena de Indias https:\/\/www.cartagena-indias.com\/Diversion\/volcan-totumo.html'
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'Recreacional',
        name: 'Parque espíritu del manglar',
        description: 'El Parque Espíritu del Manglar es un activo que combina funciones medioambientales importantes con atractivos turísticos. Principalmente, ayuda a limpiar el aire del centro de la ciudad y a controlar el flujo del agua de lluvia de las zonas cercanas; asimismo, resguarda los manglares: uno de los ecosistemas más valiosos de la ciudad, ofreciendo una experiencia turística inmersiva en un entorno Natural único.\n\nDe igual forma, el parque alberga veinte esculturas de las personalidades más importantes del departamento Bolívar y se puede usar la App Soundwalkrs que permite conocer la historia de estas. Se recomienda verificar que el parque está abierto antes de asistir ya que es común que cierre para preservar los manglares.\n',
        line: '',
        images: ['/assets/espiritu-manglar.jpg'],
        line: '',
        latitude: 10.428605330064272, 
        longitude: -75.54214968959275,
        ref: ''
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'Recreacional',
        name: 'Aviario nacional',
        description: 'El Aviario Nacional de Barú se destaca como un patrimonio Natural esencial para Cartagena, desempeñando un papel fundamental en el fomento del turismo sostenible y de naturaleza en la región. Este hermoso lugar alberga tres ecosistemas distintos: selva, costa y desierto, así como dos áreas especialmente adaptadas para aves migratorias. Situado en un sendero elevado de 6 metros, abarca alrededor de 2000 aves pertenecientes a 160 especies diversas, distribuidas en una extensión de siete hectáreas de terreno (Aviario nacional de Colombia, 2023). A pesar de ser una de las joyas naturales menos conocidas de Cartagena, el aviario posee una magia incomparable que permite a los visitantes embarcarse en un tour lleno de emociones, colores y curiosidad. Desde las famosas guacamayas y flamencos hasta especies endémicas, cada rincón del aviario ofrece una experiencia única. Más allá de ser un santuario para las aves, el aviario se presenta como un lugar donde el mundo se despliega ante los ojos de cada turista, llamados a descubrir la belleza y diversidad de una Cartagena con las alas abiertas al mundo.',
        images: ['/assets/aviario.jpg'],
        line: '',
        latitude: 10.209051964349474, 
        longitude: -75.6063483614067,
        ref: 'Foto tomada de: https:\/\/www.viator.com\/es-VE\/tours\/Isla-Baru\/Aviario-Nacional-de-Colombia-Admission-Ticket\/d50395-76432P1'
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'Recreacional',
        name: 'Jardín Botánico de Cartagena Guillermo Piñeros',
        description: 'A 30 minutos de Cartagena se encuentra el espléndido Jardín Botánico de Cartagena, un lugar donde se encuentra uno de los últimos bosques nativos vírgenes de la región y es por esta razón, que es un importante recurso para la restauración del bosque seco tropical (Jardín Botánico de Cartagena Guillermo Piñeres, s.f.).\nEs un  maravilloso oasis de naturaleza donde el turista tendrá la oportunidad de dejar atrás el bullicio de la ciudad y adentrarse en un mundo verde que alberga una gran variedad de flores, pájaros, monos, mariposas y muchas más especies autóctonas del caribe colombiano. Entre ellas se encuentra un magnífico árbol llamado: Macondo. A pesar de que hace años era muy común verlo por todo el Caribe, prácticamente ha desaparecido a causa de la deforestación (José Luis Ropero, 2020), es por esto, que no te puedes perder la oportunidad de ver este imponente árbol en todo su esplendor.\n Pero más allá de su belleza estética, el Jardín Botánico de Cartagena cumple una función crucial en la conservación de la biodiversidad, al resguardar un gran número de especies que se encuentran en peligro de extinción. ',
        line: '',
        images: ['/assets/JardinBotanicoCgena (1).jpg', '/assets/JardinBotanicoCgena (2).jpg', '/assets/JardinBotanicoCgena (3).jpg', '/assets/JardinBotanicoCgena (4).jpg'],
        latitude: 10.353107543852357, 
        longitude: -75.42868290459188,
        ref: ''
       },
       {
        category: 'Patrimonio Natural',
        subcategory: 'Recreacional',
        name: 'Tierra Bomba ',
        description: 'La isla de Tierra Bomba se encuentra al sur de Cartagena y al norte de la isla de Barú. Pertenece al departamento de Bolívar y jugó un rol clave para la defensa de Cartagena durante la época colonial. En la actualidad hay una gran cantidad de consejos comunitarios ubicados allí, por lo que se concentran una gran cantidad de saberes importantes para la identidad de Cartagena. De igual manera, es un destino que engloba belleza Natural, cultura e historia ya que cuenta con manglares, tradiciones ancestrales, y ruinas históricas. Asimismo, alberga un ecosistema con una gran cantidad de vegetación que sirve de hábitat a muchas especies.',
        line: '',
        images: ['/assets/tierra-bomba.webp'],
        latitude: 10.352649333404912, 
        longitude: -75.56748998647379,
        ref: 'Foto tomada de: https:\/\/vistamarecartagena.com\/blog\/ven-a-conocer-la-isla-de-tierra-bomba\/'
       },
       {
        category: 'Patrimonio Material',
        subcategory: 'Patrimonio Material',
        name: 'Fuerte de San Fernando',
        description: 'Con forma de herradura hacia el mar y dos grandes baluartes en el frente norte que mira hacia tierra, llamados del Rey y de la Reina (fortificaciones Cartagena), el Fuerte de San Fernando se alza como un vigía histórico frente a la bahía de Cartagena. Construido sobre los restos de un antiguo fuerte, sus muros de piedra han presenciado siglos de batallas navales, siendo un punto estratégico en la defensa de la ciudad. Esta maravilla arquitectónica y de defensa se encuentra en Bocachica y fue denominado San Fernando en honor al monarca reinante Fernando VI. Actualmente, se pueden visitar las instalaciones, enriquecerse de la historia y presenciar el lugar donde Cartagena se defendió de ataques importantes.',
        images: ['/assets/Fuerte San Fernando.jpg'],
        line: '',
        latitude: 10.319276864923877, 
        longitude: -75.58114015449107,
        ref: ''
       },
       {
        category: 'Patrimonio Material',
        subcategory: 'Patrimonio Material',
        name: 'Los hornos de Bocachica',
        description: 'Los hornos de Bocachica, ubicados en la región norte e insular de Cartagena. Especialmente en Tierra Bomba, Barú, y Manzanillo, fueron necesarios para el desarrollo de la ciudad en la época de la colonia.. Se destacan entre estos hornos los gemelos y El Gran Diablo que aún se conservan en medio de los patios y calles de Caño del Oro como es el caso del último que se encuentra en la propiedad de las familias de Julio Torres y Julio Villa, heredado de su bisabuela, es un ejemplo palpable de la historia y el legado de estos hornos.. Fueron el motor de construcción de Cartagena. Alfonso Cabrera, del Instituto de Patrimonio y Cultura de Cartagena (IPCC), afirma que: \'No habría Cartagena sin los hornos\'. Estas estructuras tradicionales, utilizadas para la fabricación de cal en la época colonial, proveían el Material necesario para la construcción de herramientas que posteriormente serian  utilizadas para crear los fuertes que defendían la ciudad. En un esfuerzo por preservar este patrimonio, la Fundación Vigías de Carex ha creado una ruta que comprende los 38 hornos existentes, permitiendo a los visitantes adentrarse en este capítulo fundamental de la historia de Cartagena. ',
        line: '',
        images: ['/assets/Hornos.JPG'],
        latitude: 10.325559045528562, 
        longitude: -75.58059418818365,
        ref: ''
       },
       {
        category: 'Patrimonio Material',
        subcategory: 'Patrimonio Material',
        name: 'Batería del ángel de San Rafael',
        description: 'En la isla de Tierrabomba, se encuentra la Batería del Ángel San Rafael: una fortificación que se construyó para vigilar la entrada a la bahía de Cartagena de Indias. Se construyó en 1762 por orden de Antonio de Arévalo, siguiendo las recomendaciones de Antonio de Sala. Es una obra maestra de la ingeniería militar española que tenía como objetivo proteger a Bocachica de los ataques enemigos (Batería del Ángel San Rafael., s.f).\n\nLa batería tiene forma de media luna irregular y está rodeada por un foso seco. Tiene una casa fuerte, un tendal, una garita y un aljibe, rastros de la vida militar. También conserva la antigua cocina de la guarnición (Batería del Ángel San Rafael., s.f).\n\nEn el año 1995 se realizó una meticulosa restauración a cargo del Instituto Nacional de Vías (INVIAS) y desde entonces la Batería del Ángel San Rafael abrió sus puertas al público. Hoy en día, los visitantes pueden recorrer sus pasajes y adentrarse en la historia que rodea esta fortificación disfrutando de una vista panorámica incomparable (Batería del Ángel San Rafael., s.f).',
        images: ['/assets/Batería del angel.png'],
        line: '',
        latitude: 10.329446732780946, 
        longitude: -75.58023439205485,
        ref: ''
       },
       {
        category: 'Patrimonio Material',
        subcategory: 'Patrimonio Material',
        name: 'Fuerte de San Jose',
        description: 'Ubicado en la isla de Tierra Bomba y construido entre 1763 y 1776 bajo la dirección del ingeniero español Antonio Arévalo, este fuerte complementaba el sistema defensivo de Cartagena para proteger la entrada a la bahía interna de Cartagena. A lo largo de su historia, el fuerte resistió ataques importantes, como el Sitio de Cartagena en 1782, y fue tomado por las tropas independentistas en 1821 (Escuela taller, s\/f). El fuerte de San jose mucho más allá de ser una construcción de carácter militar y estratégico de la historia colonial; es una muestra del rico patrimonio cultural de la ciudad y como este represente la resistencia y el valor de un pueblo que le hizo frente a la guerra. Fue restaurado en 1968 para revivir su arquitectura militar, permitiendo que hoy en día, funcione como un “museo” y atractivo turístico por sus murallas, tuéneles y cañones (Escuela taller, s\/f).  ',
        images: ['/assets/san-jose.jpg'],
        line: '',
        latitude: 10.31440532173562, 
        longitude: -75.57849323627795,
        ref: 'Foto tomada de: https:\/\/www.eluniversal.com.co\/suplementos\/facetas\/fuertes-de-san-fernando-y-san-jose-en-riesgo-por-aumento-del-nivel-del-mar-YREU18625'
       },
       {
        category: 'Patrimonio Material',
        subcategory:  'Patrimonio Material',
        name: 'Monumento a Benkos Biohò',
        description: 'El monumento Benko Biohó, construido en 1999 en la plaza principal de San Basilio de Palenque, que lleva su nombre, representa mucho más que una simple estatua. Es un símbolo de la rica historia libertaria de la comunidad palenquera, un homenaje a la memoria ancestral y un recordatorio del legado de resistencia y lucha de Benko Biohó y su pueblo cimarrón.\nEl monumento nos remonta a la época colonial, cuando hombres y mujeres africanos esclavizados se rebelaron contra la opresión y fundaron palenques, comunidades libres donde podían vivir en sus propios términos. Además, el monumento, no solo rinde homenaje a un líder individual, sino también a la memoria ancestral de la comunidad palenquera. Es un símbolo de su identidad cultural, su historia de resistencia y su invaluable contribución a la historia nacional, local y departamental.',
        images: ['/assets/Benkos (1).jpg', '/assets/Benkos (2).jpg', '/assets/Benkos (3).jpg', '/assets/Benkos (4).jpg'],
        line: '',
        latitude: 10.104322688460893, 
        longitude: -75.20019056226649,
        ref: ''
       },  
       {
        category: 'Patrimonio Material',
        subcategory: 'Patrimonio Material',
        name: 'Leprocomio en caño del oro (historia)',
        description: 'Siendo un lugar que carecía de condiciones y con construcciones precarias, el Leprocomio en caño del oro fue un lugar al que trasladaron a los leprosos en 1970 (Fortificaciones Cartagena), llegando a albergar a 600 personas. Fue ubicado en Bocachica y tan solo contaba con una iglesia y alrededor, una pared que la encerraba, con espacio para unas precarias chozas de bahareque y paja.  Aislados y en condiciones precarias, los enfermos enfrentaban no solo la enfermedad, sino también el estigma social. En otras palabras, el destierro. Se dice que en 1815 durante el cerco de Pablo Morillo a la ciudad, en Tierra Bomba se presentaron combates entre patriotas y españoles. En medio del conflicto, el general venezolano Francisco Tomás Morales, subalterno de Murillo, mandó a asesinar a todos los enfermos y a quemar las chozas. ',
        images: ['/assets/Leprocomio (1).jpg', '/assets/Leprocomio (2).jpg'],
        line: '',
        latitude: 10.342231172077012, 
        longitude: -75.54479287157082,
        ref: ''
       }

  ];